# Generated by Django 5.2.5 on 2025-09-03 11:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('reason', models.TextField()),
                ('category', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('employee', 'Employee'), ('intern', 'Intern')], max_length=50)),
                ('designated_attendee', models.CharField(choices=[('member1', 'Member 1'), ('member2', 'Member 2')], max_length=50)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('pending_reschedule', 'Pending Reschedule')], default='pending', max_length=20)),
                ('reschedule_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('original_date', models.DateField(blank=True, null=True)),
                ('original_time', models.TimeField(blank=True, null=True)),
                ('rescheduled_date', models.DateField(blank=True, null=True)),
                ('rescheduled_time', models.TimeField(blank=True, null=True)),
                ('reschedule_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment Entry',
                'verbose_name_plural': 'Appointment Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionistUserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Receptionist User',
                'verbose_name_plural': 'Receptionist Users',
                'db_table': 'receptionistuserauth',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('user_remarks', models.TextField(blank=True, null=True)),
                ('attendee_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkinout', to='register.entry')),
            ],
        ),
    ]
