# Generated by Django 5.2.5 on 2025-09-08 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinout',
            options={'ordering': ['-created_at'], 'verbose_name': 'Check-in/Check-out Record', 'verbose_name_plural': 'Check-in/Check-out Records'},
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkinouts', to='register.entry'),
        ),
    ]
