# Generated by Django 5.2.5 on 2025-09-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_checkinout_options_alter_checkinout_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
