# Generated by Django 5.2.5 on 2025-09-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_entry_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether reminder email was sent for this appointment.'),
        ),
    ]
